# Generated by Django 4.2.7 on 2026-03-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_jp', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('generated', 'Gerado'), ('sent', 'Enviado')], default='pending', max_length=20)),
                ('last_generated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
