# Generated by Django 4.2.7 on 2026-07-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_collaboratormachine_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='date_fired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='date_hired',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='machine',
            name='date_purchase',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='machine',
            name='date_sold_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='last_purchase_date',
            field=models.DateField(),
        ),
    ]
