# Generated by Django 4.2.7 on 2026-03-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaboratormachine',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='collaboratorsoftware',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='antivirus',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='antivirus_records', to='core.machine'),
        ),
        migrations.AlterField(
            model_name='cellphone',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cellphones', to='core.collaborator'),
        ),
        migrations.AlterField(
            model_name='collaboratormachine',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborator_machines', to='core.collaborator'),
        ),
        migrations.AlterField(
            model_name='collaboratormachine',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborator_machines', to='core.machine'),
        ),
        migrations.AlterField(
            model_name='collaboratorsoftware',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborator_software', to='core.collaborator'),
        ),
        migrations.AlterField(
            model_name='collaboratorsoftware',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborator_software', to='core.software'),
        ),
        migrations.AlterField(
            model_name='datadestroyed',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_destroyed_records', to='core.machine'),
        ),
        migrations.AlterField(
            model_name='email',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='core.collaborator'),
        ),
        migrations.AlterField(
            model_name='pendrive',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pen_drives', to='core.collaborator'),
        ),
        migrations.AlterField(
            model_name='server',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='core.machine'),
        ),
        migrations.AlterField(
            model_name='serveraccess',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='server_accesses', to='core.collaborator'),
        ),
        migrations.AlterField(
            model_name='servererpaccess',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erp_accesses', to='core.collaborator'),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wifi_records', to='core.collaborator'),
        ),
        migrations.AddConstraint(
            model_name='collaboratormachine',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('collaborator', 'machine'), name='unique_active_collaborator_machine'),
        ),
        migrations.AddConstraint(
            model_name='collaboratorsoftware',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('collaborator', 'software'), name='unique_active_collaborator_software'),
        ),
    ]
